# github action - settings from https://github.com/Gnimuc/CImGui.jl/blob/master/.github/workflows/ci.yml
name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [1.6.4, 1.7.2]
        arch: [x64]
        os: [ubuntu-latest]
        include:
          - version: nightly
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: sudo apt-get install xvfb && Xvfb :99 &
        if: matrix.os == 'ubuntu-latest'
      - uses: julia-actions/setup-julia@latest
      - run: julia --project=@. -e 'using Pkg; pkg"dev CImGui"' # CImGui 1.82
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        env:
          DISPLAY: :99
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
